src/java/jpa/entities/Consultant.java
package jpa.entities;

import java.io.Serializable;
import java.util.Collection;
import java.util.Date;
import javax.persistence.Basic;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.Lob;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 *
 * @author nbuser
 */
@Entity
@Table(name = "consultant")
@NamedQueries({
    @NamedQuery(name = "Consultant.findAll", query = "SELECT c FROM Consultant c"),
    @NamedQuery(name = "Consultant.findByConsultantId", query = "SELECT c FROM Consultant c WHERE c.consultantId = :consultantId"),
    @NamedQuery(name = "Consultant.findByEmail", query = "SELECT c FROM Consultant c WHERE c.email = :email"),
    @NamedQuery(name = "Consultant.findByPrenom", query = "SELECT c FROM Consultant c WHERE c.prenom = :prenom"),
    @NamedQuery(name = "Consultant.findByStatusId", query = "SELECT c FROM Consultant c WHERE c.statusId = :statusId"),
    @NamedQuery(name = "Consultant.findByNom", query = "SELECT c FROM Consultant c WHERE c.nom = :nom")})
public class Consultant implements Serializable {
    private static final long serialVersionUID = 1L;
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Basic(optional = false)
    @Column(name = "consultant_id")
    private Integer consultantId;
    @Basic(optional = false)
    @Column(name = "email")
    private String email;
    @Basic(optional = false)
    @Column(name = "prenom")
    private String prenom;
    @Basic(optional = false)
    @Column(name = "nom")
    private String nom;
    @JoinColumn(name = "status_id", referencedColumnName = "status_id")
    @ManyToOne(optional = false)
    private ConsultantStatus statusId;
    @OneToMany(cascade = CascadeType.ALL, mappedBy = "consultantId")
    private Collection<Depot> depotCollection;

    public Consultant() {
    }

    public Consultant(Integer consultantId) {
        this.consultantId = consultantId;
    }

    public Consultant(Integer consultantId, String email, String prenom, ConsultantStatus statusId, String nom) {
        this.consultantId = consultantId;
        this.email = email;
        this.prenom = prenom;
        this.nom = nom;
        this.statusId=statusId;
    }

    public Integer getConsultantId() {
        return consultantId;
    }

    public void setConsultantId(Integer consultantId) {
        this.consultantId = consultantId;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getPrenom() {
        return prenom;
    }

    public void setPrenom(String prenom) {
        this.prenom = prenom;
    }

    

    public String getNom() {
        return nom;
    }

    public void setNom(String nom) {
        this.nom = nom;
    }


    public ConsultantStatus getStatusId() {
        return statusId;
    }

    public void setStatusId(ConsultantStatus statusId) {
        this.statusId = statusId;
    }

    public Collection<Depot> getDepotCollection() {
        return depotCollection;
    }

    public void setDepotCollection(Collection<Depot> depotCollection) {
        this.depotCollection = depotCollection;
    }

    @Override
    public int hashCode() {
        int hash = 0;
        hash += (consultantId != null ? consultantId.hashCode() : 0);
        return hash;
    }

    @Override
    public boolean equals(Object object) {
        // TODO: Warning - this method won't work in the case the id fields are not set
        if (!(object instanceof Consultant)) {
            return false;
        }
        Consultant other = (Consultant) object;
        if ((this.consultantId == null && other.consultantId != null) || (this.consultantId != null && !this.consultantId.equals(other.consultantId))) {
            return false;
        }
        return true;
    }

    @Override
    public String toString() {
        return "jpa.entities.Consultant[consultantId=" + consultantId + "]";
    }

}

src/java/jsf/ConsultantController.java
package jsf;

import jpa.entities.Consultant;
import jsf.util.JsfUtil;
import jsf.util.PaginationHelper;
import jpa.session.ConsultantFacade;

import java.util.ResourceBundle;
import javax.ejb.EJB;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import javax.faces.component.UIComponent;
import javax.faces.context.FacesContext;
import javax.faces.convert.Converter;
import javax.faces.convert.FacesConverter;
import javax.faces.model.DataModel;
import javax.faces.model.ListDataModel;
import javax.faces.model.SelectItem;

@ManagedBean (name="consultantController")
@SessionScoped
public class ConsultantController {

    private Consultant current;
    private DataModel items = null;
    @EJB private jpa.session.ConsultantFacade ejbFacade;
    private PaginationHelper pagination;
    private int selectedItemIndex;

    public ConsultantController() {
    }

    public Consultant getSelected() {
        if (current == null) {
            current = new Consultant();
            selectedItemIndex = -1;
        }
        return current;
    }

    private ConsultantFacade getFacade() {
        return ejbFacade;
    }

    public PaginationHelper getPagination() {
        if (pagination == null) {
            pagination = new PaginationHelper(10) {

                @Override
                public int getItemsCount() {
                    return getFacade().count();
                }

                @Override
                public DataModel createPageDataModel() {
                    return new ListDataModel(getFacade().findRange(new int[]{getPageFirstItem(), getPageFirstItem()+getPageSize()}));
                }
            };
        }
        return pagination;
    }

    public String prepareList() {
        recreateModel();
        return "List";
    }

    public String prepareView() {
        current = (Consultant)getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        return "View";
    }

    public String prepareCreate() {
        current = new Consultant();
        selectedItemIndex = -1;
        return "Create";
    }

    public String create() {
        try {
            getFacade().create(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/resources/Bundle").getString("ConsultantCreated"));
            return prepareCreate();
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/resources/Bundle").getString("PersistenceErrorOccured"));
            return null;
        }
    }

    public String prepareEdit() {
        current = (Consultant)getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        return "Edit";
    }

    public String update() {
        try {
            getFacade().edit(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/resources/Bundle").getString("ConsultantUpdated"));
            return "View";
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/resources/Bundle").getString("PersistenceErrorOccured"));
            return null;
        }
    }

    public String destroy() {
        current = (Consultant)getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        performDestroy();
        recreateModel();
        return "List";
    }

    public String destroyAndView() {
        performDestroy();
        recreateModel();
        updateCurrentItem();
        if (selectedItemIndex >= 0) {
            return "View";
        } else {
            // all items were removed - go back to list
            recreateModel();
            return "List";
        }
    }

    private void performDestroy() {
        try {
            getFacade().remove(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/resources/Bundle").getString("ConsultantDeleted"));
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/resources/Bundle").getString("PersistenceErrorOccured"));
        }
    }

    private void updateCurrentItem() {
        int count = getFacade().count();
        if (selectedItemIndex >= count) {
            // selected index cannot be bigger than number of items:
            selectedItemIndex = count-1;
            // go to previous page if last page disappeared:
            if (pagination.getPageFirstItem() >= count) {
                pagination.previousPage();
            }
        }
        if (selectedItemIndex >= 0) {
            current = getFacade().findRange(new int[]{selectedItemIndex, selectedItemIndex+1}).get(0);
        }
    }

    public DataModel getItems() {
        if (items == null) {
            items = getPagination().createPageDataModel();
        }
        return items;
    }

    private void recreateModel() {
        items = null;
    }

    public String next() {
        getPagination().nextPage();
        recreateModel();
        return "List";
    }

    public String previous() {
        getPagination().previousPage();
        recreateModel();
        return "List";
    }

    public SelectItem[] getItemsAvailableSelectMany() {
        return JsfUtil.getSelectItems(ejbFacade.findAll(), false);
    }

    public SelectItem[] getItemsAvailableSelectOne() {
        return JsfUtil.getSelectItems(ejbFacade.findAll(), true);
    }

    @FacesConverter(forClass=Consultant.class)
    public static class ConsultantControllerConverter implements Converter {

        public Object getAsObject(FacesContext facesContext, UIComponent component, String value) {
            if (value == null || value.length() == 0) {
                return null;
            }
            ConsultantController controller = (ConsultantController)facesContext.getApplication().getELResolver().
                    getValue(facesContext.getELContext(), null, "consultantController");
            return controller.ejbFacade.find(getKey(value));
        }

        java.lang.Integer getKey(String value) {
            java.lang.Integer key;
            key = Integer.valueOf(value);
            return key;
        }

        String getStringKey(java.lang.Integer value) {
            StringBuffer sb = new StringBuffer();
            sb.append(value);
            return sb.toString();
        }

        public String getAsString(FacesContext facesContext, UIComponent component, Object object) {
            if (object == null) {
                return null;
            }
            if (object instanceof Consultant) {
                Consultant o = (Consultant) object;
                return getStringKey(o.getConsultantId());
            } else {
                throw new IllegalArgumentException("object " + object + " is of type " + object.getClass().getName() + "; expected type: "+ConsultantController.class.getName());
            }
        }

    }

}

web/consultant/Create.xhtml
<?xml version="1.0" encoding="ISO-8859-1" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.CreateConsultantTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:panelGroup id="messagePanel" layout="block">
                <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
            </h:panelGroup>
            <h:form>
                <h:panelGrid columns="2">
                    <h:outputLabel value="#{bundle.CreateConsultantLabel_consultantId}" for="consultantId" />
                    <h:inputText id="consultantId" value="#{consultantController.selected.consultantId}" title="#{bundle.CreateConsultantTitle_consultantId}" required="true" requiredMessage="#{bundle.CreateConsultantRequiredMessage_consultantId}"/>
                    <h:outputLabel value="#{bundle.CreateConsultantLabel_statusId}" for="statusId" />
                    <h:inputText id="statusId" value="#{consultantController.selected.statusId}" title="#{bundle.CreateConsultantTitle_statusId}" required="true" requiredMessage="#{bundle.CreateConsultantRequiredMessage_statusId}"/>
                    <h:outputLabel value="#{bundle.CreateConsultantLabel_email}" for="email" />
                    <h:inputText id="email" value="#{consultantController.selected.email}" title="#{bundle.CreateConsultantTitle_email}" required="true" requiredMessage="#{bundle.CreateConsultantRequiredMessage_email}"/>
                    <h:outputLabel value="#{bundle.CreateConsultantLabel_prenom}" for="prenom" />
                    <h:inputText id="prenom" value="#{consultantController.selected.prenom}" title="#{bundle.CreateConsultantTitle_prenom}" required="true" requiredMessage="#{bundle.CreateConsultantRequiredMessage_prenom}"/>
                    <h:outputLabel value="#{bundle.CreateConsultantLabel_nom}" for="nom" />
                    <h:inputText id="nom" value="#{consultantController.selected.nom}" title="#{bundle.CreateConsultantTitle_nom}" required="true" requiredMessage="#{bundle.CreateConsultantRequiredMessage_nom}"/>                                   
<!--                    <h:outputLabel value="#{bundle.CreateConsultantLabel_statusId}" for="statusId" />-->
<!--                        <h:selectOneMenu id="statusId" value="#{consultantController.selected.statusId}" title="#{bundle.CreateConsultantTitle_statusId}" required="true" requiredMessage="#{bundle.CreateConsultantRequiredMessage_statusId}">
                            <f:selectItems value="#{consultantStatusController.itemsAvailableSelectOne}"/>
                        </h:selectOneMenu>-->
                </h:panelGrid>
                <br />
                <h:commandLink action="#{consultantController.create}" value="#{bundle.CreateConsultantSaveLink}" />
                <br />
                <br />
                <h:commandLink action="#{consultantController.prepareList}" value="#{bundle.CreateConsultantShowAllLink}" immediate="true"/>
                <br />
                <br />
                <h:commandLink value="#{bundle.CreateConsultantIndexLink}" action="/index" immediate="true" />
            </h:form>
        </ui:define>
    </ui:composition>

</html>

web/consultant/Edit.xhtml
<?xml version="1.0" encoding="ISO-8859-1" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.EditConsultantTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:panelGroup id="messagePanel" layout="block">
                <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
            </h:panelGroup>
            <h:form>
                <h:panelGrid columns="2">
                    <h:outputLabel value="#{bundle.EditConsultantLabel_consultantId}" for="consultantId" />
                    <h:inputText id="consultantId" value="#{consultantController.selected.consultantId}" title="#{bundle.EditConsultantTitle_consultantId}" required="true" requiredMessage="#{bundle.EditConsultantRequiredMessage_consultantId}"/>
                    <h:outputLabel value="#{bundle.EditConsultantLabel_email}" for="email" />
                    <h:inputText id="email" value="#{consultantController.selected.email}" title="#{bundle.EditConsultantTitle_email}" required="true" requiredMessage="#{bundle.EditConsultantRequiredMessage_email}"/>
                    <h:outputLabel value="#{bundle.EditConsultantLabel_statusId}" for="statusId" />
                    <h:inputText id="statusId" value="#{consultantController.selected.statusId}" title="#{bundle.EditConsultantTitle_statusId}" required="true" requiredMessage="#{bundle.EditConsultantRequiredMessage_statusId}"/>
                    <h:outputLabel value="#{bundle.EditConsultantLabel_prenom}" for="prenom" />
                    <h:inputText id="prenom" value="#{consultantController.selected.prenom}" title="#{bundle.EditConsultantTitle_prenom}" required="true" requiredMessage="#{bundle.EditConsultantRequiredMessage_prenom}"/>
                    <h:outputLabel value="#{bundle.EditConsultantLabel_nom}" for="nom" />
                    <h:inputText id="nom" value="#{consultantController.selected.nom}" title="#{bundle.EditConsultantTitle_nom}" required="true" requiredMessage="#{bundle.EditConsultantRequiredMessage_nom}"/>                
                    <h:outputLabel value="#{bundle.EditConsultantLabel_statusId}" for="statusId" />
                    <h:selectOneMenu id="statusId" value="#{consultantController.selected.statusId}" title="#{bundle.EditConsultantTitle_statusId}" required="true" requiredMessage="#{bundle.EditConsultantRequiredMessage_statusId}">
                        <f:selectItems value="#{consultantStatusController.itemsAvailableSelectOne}"/>
                    </h:selectOneMenu>
                </h:panelGrid>
                <h:commandLink action="#{consultantController.update}" value="#{bundle.EditConsultantSaveLink}"/>
                <br />
                <br />
                <h:commandLink action="View" value="#{bundle.EditConsultantViewLink}" immediate="true"/>
                <br />
                <h:commandLink action="#{consultantController.prepareList}" value="#{bundle.EditConsultantShowAllLink}" immediate="true"/>
                <br />
                <br />
                <h:commandLink value="#{bundle.EditConsultantIndexLink}" action="/index" immediate="true" />
            </h:form>
        </ui:define>
    </ui:composition>

</html>

web/consultant/List.xhtml
<?xml version="1.0" encoding="ISO-8859-1" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.ListConsultantTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
        <h:form styleClass="jsfcrud_list_form">
            <h:panelGroup id="messagePanel" layout="block">
                <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
            </h:panelGroup>
            <h:outputText escape="false" value="#{bundle.ListConsultantEmpty}" rendered="#{consultantController.items.rowCount == 0}"/>
            <h:panelGroup rendered="#{consultantController.items.rowCount > 0}">
                <h:outputText value="#{consultantController.pagination.pageFirstItem + 1}..#{consultantController.pagination.pageLastItem + 1}/#{consultantController.pagination.itemsCount}"/>&nbsp;
                <h:commandLink action="#{consultantController.previous}" value="#{bundle.Previous} #{consultantController.pagination.pageSize}" rendered="#{consultantController.pagination.hasPreviousPage}"/>&nbsp;
                <h:commandLink action="#{consultantController.next}" value="#{bundle.Next} #{consultantController.pagination.pageSize}" rendered="#{consultantController.pagination.hasNextPage}"/>&nbsp;
                <h:dataTable value="#{consultantController.items}" var="item" border="0" cellpadding="2" cellspacing="0" rowClasses="jsfcrud_odd_row,jsfcrud_even_row" rules="all" style="border:solid 1px">
                    <h:column>
                        <f:facet name="header">
                            <h:outputText value="#{bundle.ListConsultantTitle_consultantId}"/>
                        </f:facet>
                        <h:outputText value="#{item.consultantId}"/>
                    </h:column>
                    <h:column>
                        <f:facet name="header">
                            <h:outputText value="#{bundle.ListConsultantTitle_email}"/>
                        </f:facet>
                        <h:outputText value="#{item.email}"/>
                    </h:column>
                    <h:column>
                        <f:facet name="header">
                            <h:outputText value="#{bundle.ListConsultantTitle_statusId}"/>
                        </f:facet>
                        <h:outputText value="#{item.statusId}"/>
                    </h:column>
                    <h:column>
                        <f:facet name="header">
                            <h:outputText value="#{bundle.ListConsultantTitle_prenom}"/>
                        </f:facet>
                        <h:outputText value="#{item.prenom}"/>
                    </h:column>
                    <h:column>
                        <f:facet name="header">
                            <h:outputText value="#{bundle.ListConsultantTitle_nom}"/>
                        </f:facet>
                        <h:outputText value="#{item.nom}"/>
                    </h:column>                                     
                    <h:column>
                        <f:facet name="header">
                            <h:outputText value="#{bundle.ListConsultantTitle_statusId}"/>
                        </f:facet>
                        <h:outputText value="#{item.statusId}"/>
                    </h:column>
                    <h:column>
                        <f:facet name="header">
                            <h:outputText value="&nbsp;"/>
                        </f:facet>
                        <h:commandLink action="#{consultantController.prepareView}" value="#{bundle.ListConsultantViewLink}"/>
                        <h:outputText value=" "/>
                        <h:commandLink action="#{consultantController.prepareEdit}" value="#{bundle.ListConsultantEditLink}"/>
                        <h:outputText value=" "/>
                        <h:commandLink action="#{consultantController.destroy}" value="#{bundle.ListConsultantDestroyLink}"/>
                    </h:column>
                </h:dataTable>
            </h:panelGroup>
            <br />
            <h:commandLink action="#{consultantController.prepareCreate}" value="#{bundle.ListConsultantCreateLink}"/>
            <br />
            <br />
            <h:commandLink value="#{bundle.ListConsultantIndexLink}" action="/index" immediate="true" />
        </h:form>
        </ui:define>
    </ui:composition>

</html>

web/consultant/View.xhtml
<?xml version="1.0" encoding="ISO-8859-1" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.ViewConsultantTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:panelGroup id="messagePanel" layout="block">
                <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
            </h:panelGroup>
            <h:form>
                <h:panelGrid columns="2">
                    <h:outputText value="#{bundle.ViewConsultantLabel_consultantId}"/>
                    <h:outputText value="#{consultantController.selected.consultantId}" title="#{bundle.ViewConsultantTitle_consultantId}"/>
                    <h:outputText value="#{bundle.ViewConsultantLabel_email}"/>
                    <h:outputText value="#{consultantController.selected.email}" title="#{bundle.ViewConsultantTitle_email}"/>
                    <h:outputText value="#{bundle.ViewConsultantLabel_statusId}"/>
                    <h:outputText value="#{consultantController.selected.statusId}" title="#{bundle.ViewConsultantTitle_statusId}"/>
                    <h:outputText value="#{bundle.ViewConsultantLabel_prenom}"/>
                    <h:outputText value="#{consultantController.selected.prenom}" title="#{bundle.ViewConsultantTitle_prenom}"/>
                    <h:outputText value="#{bundle.ViewConsultantLabel_nom}"/>
                    <h:outputText value="#{consultantController.selected.nom}" title="#{bundle.ViewConsultantTitle_nom}"/>                   
                    <h:outputText value="#{bundle.ViewConsultantLabel_statusId}"/>
                    <h:outputText value="#{consultantController.selected.statusId}" title="#{bundle.ViewConsultantTitle_statusId}"/>
                </h:panelGrid>
                <br />
                <h:commandLink action="#{consultantController.destroyAndView}" value="#{bundle.ViewConsultantDestroyLink}"/>
                <br />
                <br />
                <h:commandLink action="Edit" value="#{bundle.ViewConsultantEditLink}"/>
                <br />
                <h:commandLink action="#{consultantController.prepareCreate}" value="#{bundle.ViewConsultantCreateLink}" />
                <br />
                <h:commandLink action="#{consultantController.prepareList}" value="#{bundle.ViewConsultantShowAllLink}"/>
                <br />
                <br />
                <h:commandLink value="#{bundle.ViewConsultantIndexLink}" action="/index" immediate="true" />

            </h:form>
        </ui:define>
    </ui:composition>

</html>